name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas openpyxl pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole app.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: validador-mimc-exe
          path: dist/*.exe
